// Generated by bun run gen:extension-types; edit modules/extensions/infrastructure/templates/*/extension.yaml instead.
export interface ExtensionSpecs {
  "cloudflareWorker": { "accountId": string; "worker": string; "hostname": string; "zone": string; "database": string; "compatibilityDate": string; } | undefined;
  "imageProxy": { "image": string; "allowedSources": Array<string>; "keyEnv": string; "saltEnv": string; } | undefined;
  "monitoring": boolean | { "images": { "prometheus": string; "nodeExporter": string; "alertmanager": string; }; "zone"?: string; "hostname"?: string; "username": string; "passwordEnv"?: string; "adoptDns": boolean; "containers"?: Array<string>; "upstreams"?: Array<{ "name": string; "file": string; "healthPath": string; }>; };
  "nats": { "image": string; "tokenEnv": string; "jetstream": boolean; "syncInterval": "always" | string; "maxConnections": number; "maxPayloadKb": number; "memoryMb": number; "cpus": number; "maxMemoryMb": number; "maxFileGb": number; "dataPath": string; } | undefined;
  "postgres": { "image": string; "database": string; "username": string; "passwordEnv": string; "adminPasswordEnv": string; "migrationPasswordEnv": string; "memoryMb": number; "cpus": number; "dataPath": string; "disk"?: string; "backup"?: { "engine": "pgbackrest" | "dump"; "fullIntervalHours": number; "retentionDays"?: number; "restoreCheckSchedule": string; "maxAgeHours": number; "restoreCheckMaxAgeHours": number; "destination"?: string; "schedule"?: string; "region"?: string; }; } | undefined;
  "redis": { "image": string; "passwordEnv": string; "memoryMb": number; "maxmemoryMb": number; "appendfsync": "everysec" | "always"; "cpus": number; "dataPath": string; } | undefined;
}
