import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {definitionPaths} from '../src/modules/extensions/infrastructure/catalog';

// Types are derived from YAML JSON Schema, including parse-time defaults.
// Unsupported type constructions fail instead of silently generating `any`.
export function extensionTypes(directory = fileURLToPath(new URL('../src/modules/extensions/infrastructure/templates/', import.meta.url))) {
  function typeOf(s: any): string {
    if(s.enum) return s.enum.map((v: unknown)=>JSON.stringify(v)).join(' | ');
    if(s.const !== undefined) return JSON.stringify(s.const);
    if(s.anyOf) return s.anyOf.map(typeOf).join(' | ');
    if(s.type==='object') return '{ '+Object.entries(s.properties ?? {}).map(([k,v]:[string,any])=>`${JSON.stringify(k)}${s.required?.includes(k)||v.default!==undefined?'':'?'}: ${typeOf(v)};`).join(' ')+' }';
    if(s.type==='array') return `Array<${typeOf(s.items)}>`;
    if(s.type==='integer'||s.type==='number') return 'number';
    if(['string','boolean','null'].includes(s.type))return s.type;
    throw new Error(`Unsupported extension schema type: ${JSON.stringify(s)}`);
  }
  const declarations=definitionPaths(directory).map(f=>Bun.YAML.parse(readFileSync(f,'utf8')) as any).filter(d=>d.schema);
  return '// Generated by bun run gen:extension-types; edit modules/extensions/infrastructure/templates/*/extension.yaml instead.\nexport interface ExtensionSpecs {\n'+declarations.map(d=>`  ${JSON.stringify(d.metadata.key??d.metadata.name)}: ${typeOf(d.schema)}${d.schema.default===undefined?' | undefined':''};`).join('\n')+'\n}\n';
}
if(import.meta.main) {
  const file=new URL('../src/modules/extensions/domain/specs.generated.ts',import.meta.url);
  const expected=extensionTypes();
  if(process.argv.includes('--check')) {
    if(await Bun.file(file).text()!==expected)throw new Error('Extension types are stale; run bun run gen:extension-types');
  } else await Bun.write(file,expected);
}
